### ISSUE TITLE
A crash occured after build with dexcount-gradle-plugin

### ISSUE THREAD

**Issue by AlanDan** [KeepSafe/dexcount-gradle-plugin#108]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':teacher:countDebugDexMethods'.
> org.codehaus.groovy.runtime.DefaultGroovyMethods.each(Ljava/util/Collection;Lgroovy/lang/Closure;)Ljava/util/Collection;

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':teacher:countDebugDexMethods'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: java.lang.NoSuchMethodError: org.codehaus.groovy.runtime.DefaultGroovyMethods.each(Ljava/util/Collection;Lgroovy/lang/Closure;)Ljava/util/Collection;
        at com.getkeepsafe.dexcount.PackageTree.printPackageList(PackageTree.groovy:156)
        at com.getkeepsafe.dexcount.PackageTree.print(PackageTree.groovy:125)
        at com.getkeepsafe.dexcount.PackageTree$print$1.call(Unknown Source)
        at com.getkeepsafe.dexcount.DexMethodCountTask.print(DexMethodCountTask.groovy:215)
        at com.getkeepsafe.dexcount.DexMethodCountTask$_printFullTree_closure7.doCall(DexMethodCountTask.groovy:170)
        at com.getkeepsafe.dexcount.DexMethodCountTask$_printToFile_closure11.doCall(DexMethodCountTask.groovy:236)
        at com.getkeepsafe.dexcount.DexMethodCountTask.printToFile(DexMethodCountTask.groovy:234)
        at com.getkeepsafe.dexcount.DexMethodCountTask.printFullTree(DexMethodCountTask.groovy:169)
        at com.getkeepsafe.dexcount.DexMethodCountTask.countMethods(DexMethodCountTask.groovy:72)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 47 more

BUILD FAILED

Total time: 1 mins 2.219 secs
localhost%

**Comment by plastiv** [comment]
I also see crash after updating to Gradle 2.14. Not sure if it is connected to the crash above:
```
Caused by: java.lang.NoClassDefFoundError: org/gradle/logging/ShowStacktrace
        at com.getkeepsafe.dexcount.DexMethodCountPlugin$_applyAndroid_closure1$_closure2.doCall(DexMethodCountPlugin.groovy:62)
        at com.getkeepsafe.dexcount.DexMethodCountPlugin$_applyAndroid_closure1.doCall(DexMethodCountPlugin.groovy:48)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:165)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:159)
        at com.android.build.gradle.AppExtension.addVariant(AppExtension.java:47)
        at com.android.build.gradle.internal.ApiObjectFactory.create(ApiObjectFactory.java:113)
        at com.android.build.gradle.BasePlugin$12.call(BasePlugin.java:661)
        at com.android.build.gradle.BasePlugin$12.call(BasePlugin.java:654)
        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:47)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:653)
        at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:572)
        at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:569)
        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:47)
        at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:568)
        at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:565)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        ... 70 more
```

**Comment by benjamin-bader** [comment]
@AlanDan Thanks for the report!  Can you verify what version of Gradle you are using (i.e. paste the output of `./gradlew --version`)?

@plastiv, Thanks for confirming.  I'd be interested in the same thing from you as well, if you have time.

**Comment by plastiv** [comment]
Gradle 2.14 and dex-count-plugin 0.5.3. 
Can reproduce by running just `./gradlew`

**Comment by benjamin-bader** [comment]
Thanks, I just reproduced it.  Seems the Gradle API has changed out from underneath us... 😠

**Comment by benjamin-bader** [comment]
@plastiv tracking your crash in #109; this is distinct from the initial crash reported here.

**Comment by benjamin-bader** [comment]
@AlanDan As close as I can tell, your crash comes about because a standard Groovy method `DefaultGroovyMethods.each(Collection, Closure)` can't be found on the classpath.  Because this is a core Groovy thing, the only real cause I can think of is that you somehow have multiple versions of Groovy on the classpath at the same time, and are unlucky in their loading order.  Does any of this ring a bell?

The output of `./gradlew --version` might be helpful here, but any insight you have into your build environment would be more so.  I cannot seem to reproduce this myself.

**Comment by AlanDan** [comment]
@benjamin-bader As I'm living in China so that I can't reply you immediately. thanks for your help, and here is my gradlew' version information, please check it out.

## **-gradlew version**

Gradle 2.2.1


Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Mac OS X 10.10.5 x86_64

## **-extra information**

I'm using android studio 1.2.2, and my dependency of build.gradle is :

`'classpath 'com.android.tools.build:gradle:1.0.0'`

and with a property `android.useDeprecatedNdk=true` setting in gralde.properties file


thank you!

**Comment by benjamin-bader** [comment]
Thanks, I see the problem exactly.  You are on a version of Gradle that bundles an older version of Groovy that is slightly incompatible with the version we expect.  I can work around this enough so that the next release will work for you, but I would encourage you to update your Gradle version.  We're on 2.14 - 12 versions ahead!

Either way, I'll have a bugfix release out today.  Thanks for your report!

**Comment by AlanDan** [comment]
Glad to see this problem's got solved, and I really appreciate your help!

**Comment by Sausure** [comment]
I get the same problem when I update androidstudio to the version of 2.2.
And gradle version is
------------------------------------------------------------
Gradle 2.14.1
------------------------------------------------------------
Build time:   2016-07-18 06:38:37 UTC
Revision:     d9e2113d9fb05a5caabba61798bdb8dfdca83719

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_91 (Oracle Corporation 25.91-b15)
OS:           Windows 7 6.1 amd64


Exception:<br>
>Caused by: java.lang.NoClassDefFoundError: org/gradle/logging/ShowStacktrace
        at com.getkeepsafe.dexcount.DexMethodCountPlugin$_applyAndroid_closure1$_closure2.doCall(DexMethodCountPlugin.groovy:62)
        at com.getkeepsafe.dexcount.DexMethodCountPlugin$_applyAndroid_closure1.doCall(DexMethodCountPlugin.groovy:48)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:165)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:159)
        at com.android.build.gradle.AppExtension.addVariant(AppExtension.java:47)
        at com.android.build.gradle.internal.ApiObjectFactory.create(ApiObjectFactory.java:113)
        at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:692)
        at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:685)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:683)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.java:603)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        ... 70 more
