### ISSUE TITLE
Error when building an AAR

### ISSUE THREAD

**Issue by jaredsburrows** [KeepSafe/dexcount-gradle-plugin#116]
## Error when building an AAR

Java version: 7
Plugin version: 0.5.4

## Stacktrace
```
18:54:15 Error counting dex methods.  Please contact the developer at https://github.com/KeepSafe/dexcount-gradle-plugin/issues
18:54:15 com.getkeepsafe.dexcount.DexCountException: dx exited with exit code 1
18:54:15 stderr=Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0
18:54:15 	at java.lang.ClassLoader.defineClass1(Native Method)
18:54:15 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
18:54:15 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
18:54:15 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
18:54:15 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
18:54:15 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
18:54:15 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
18:54:15 	at java.security.AccessController.doPrivileged(Native Method)
18:54:15 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
18:54:15 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
18:54:15 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
18:54:15 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
18:54:15 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
18:54:15 
18:54:15 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
18:54:15 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
18:54:15 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
18:54:15 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
18:54:15 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
18:54:15 	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
18:54:15 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
18:54:15 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
18:54:15 	at com.getkeepsafe.dexcount.DexFile.extractDexFromAar(DexFile.groovy:126)
18:54:15 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:54:15 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:54:15 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:54:15 	at java.lang.reflect.Method.invoke(Method.java:483)
18:54:15 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
18:54:15 	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
18:54:15 	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
18:54:15 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:214)
18:54:15 	at com.getkeepsafe.dexcount.DexFile.extractDexData(DexFile.groovy:59)
18:54:15 	at com.getkeepsafe.dexcount.DexFile$extractDexData.call(Unknown Source)
18:54:15 	at com.getkeepsafe.dexcount.DexMethodCountTask.generatePackageTree(DexMethodCountTask.groovy:255)
18:54:15 	at com.getkeepsafe.dexcount.DexMethodCountTask.countMethods(DexMethodCountTask.groovy:70)
18:54:15 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:54:15 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:54:15 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:54:15 	at java.lang.reflect.Method.invoke(Method.java:483)
18:54:15 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
18:54:15 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
18:54:15 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
18:54:15 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
18:54:15 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
18:54:15 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
18:54:15 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
18:54:15 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
18:54:15 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
18:54:15 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
18:54:15 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
18:54:15 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
18:54:15 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
18:54:15 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
18:54:15 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
18:54:15 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
18:54:15 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
18:54:15 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
18:54:15 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
18:54:15 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
18:54:15 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
18:54:15 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
18:54:15 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
18:54:15 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
18:54:15 	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
18:54:15 	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
18:54:15 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
18:54:15 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
18:54:15 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
18:54:15 	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
18:54:15 	at org.gradle.internal.Factories$1.create(Factories.java:22)
18:54:15 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
18:54:15 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
18:54:15 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
18:54:15 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
18:54:15 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
18:54:15 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
18:54:15 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
18:54:15 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
18:54:15 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
18:54:15 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
18:54:15 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
18:54:15 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
18:54:15 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
18:54:15 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
18:54:15 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
18:54:15 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
18:54:15 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
18:54:15 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
18:54:15 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
18:54:15 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:54:15 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
18:54:15 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:54:15 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
18:54:15 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:54:15 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
18:54:15 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:54:15 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
18:54:15 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
18:54:15 	at org.gradle.util.Swapper.swap(Swapper.java:38)
18:54:15 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
18:54:15 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:54:15 	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:40)
18:54:15 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:54:15 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
18:54:15 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
18:54:15 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:54:15 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
18:54:15 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
18:54:15 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:54:15 	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
18:54:15 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:54:15 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
18:54:15 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
18:54:15 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
18:54:15 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
18:54:15 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
18:54:15 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
18:54:15 	at java.lang.Thread.run(Thread.java:745)
18:54:15 
```

**Comment by benjamin-bader** [comment]
Wait, I thought I knew the problem but now I see that the failure is in invoking `dx`.  The PR above will not fix this.

Basically, `dx` is compiled for JDK 8 and there isn't anything we can do about it.  You'll need to run Java 8.

I'll make a note of this.  Java 9 is coming soon, and most people run Java 8 already.  Might as well bump up to JDK 1.8.

**Comment by jaredsburrows** [comment]
The CI naturally has JDK7 so I bump it to JDK8.

I have only seen this error when using it on AARs and not APKs.

**Comment by benjamin-bader** [comment]
Right, because that's the only time we rely on Java classes that we haven't built and bundled ourselves.  Counting an AAR means finding the local system's Android SDK installation, finding `dx` inside of it, and running it.  Coming from Google as it does, that code is out of our hands.

It just cannot be run with Java 7.

**Comment by jaredsburrows** [comment]
Alright. Sounds good.

**Comment by xCatG** [comment]
I ran into this when trying to use this with Jenkins pipeline, where my slave node has both jdk 18 and 17 installed, and $JAVA_HOME is set to point to 1.8. Gradle finds the 1.8 but somehow dx still throws this error.

Is this an issue on dx, or on gradle, or on Jenkins? Just clueless on who should I ask so...

**Comment by xCatG** [comment]
I just solved my own problem; basically just make sure `${JAVA_HOME}/bin` of jdk 1.8 is the first thing in `env.PATH` so dx picks the correct one to use.
