### ISSUE TITLE
Gradle 3.0 API Breakage

### ISSUE THREAD

**Issue by benjamin-bader** [KeepSafe/dexcount-gradle-plugin#123]
Gradle 3.0 is here!  Maybe we still work with it?  Let's find out!

This issue will track general 3.0 compatibility; individual API breakages will be tracked in their own issues:

- [x] `StyledTextOutput` removed, issue #124

**Comment by EddieRingle** [comment]
@benjamin-bader It does not, unfortunately. The plugin is using an API that got moved/refactored. Stack trace:

```
Caused by: org.gradle.api.GradleException: Could not generate a proxy class for class com.getkeepsafe.dexcount.DexMethodCountTask.
	at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:201)
	at org.gradle.api.internal.AbstractClassGenerator.generate(AbstractClassGenerator.java:64)
	at org.gradle.api.internal.project.taskfactory.TaskFactory.create(TaskFactory.java:115)
	at org.gradle.api.internal.project.taskfactory.TaskFactory.createTask(TaskFactory.java:77)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.createTask(AnnotationProcessingTaskFactory.java:46)
	at org.gradle.api.internal.project.taskfactory.DependencyAutoWireTaskFactory.createTask(DependencyAutoWireTaskFactory.java:39)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:62)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:97)
	at com.getkeepsafe.dexcount.DexMethodCountPlugin.applyToVariantOutput(DexMethodCountPlugin.groovy:106)
	at com.getkeepsafe.dexcount.DexMethodCountPlugin$_applyAndroid_closure1$_closure2.doCall(DexMethodCountPlugin.groovy:78)
	at com.getkeepsafe.dexcount.DexMethodCountPlugin$_applyAndroid_closure1.doCall(DexMethodCountPlugin.groovy:77)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
	at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:172)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:166)
	at com.android.build.gradle.AppExtension.addVariant(AppExtension.java:47)
	at com.android.build.gradle.internal.ApiObjectFactory.create(ApiObjectFactory.java:113)
	at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:692)
	at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:685)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:683)
	at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
	at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
	at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.java:603)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy12.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	... 52 more
Caused by: java.lang.NoClassDefFoundError: org/gradle/logging/StyledTextOutput
	at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:67)
	at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:51)
	at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:31)
	at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:260)
	at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:216)
	at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:95)
	... 89 more
Caused by: java.lang.ClassNotFoundException: org.gradle.logging.StyledTextOutput
	... 95 more

```

**Comment by benjamin-bader** [comment]
Thanks, @EddieRingle.  It's our old friend, `StyledTextOutput`; I missed that it was being removed.  Bummer!

I'll open a new issue for this particular class; undoubtedly there will be others.

**Comment by EddieRingle** [comment]
@benjamin-bader 0.5.6 seems to resolve our issues, thanks!

**Comment by benjamin-bader** [comment]
Great, glad to hear it.  Thanks for reporting!

**Comment by ewoks** [comment]
Just for records and others who stumble upon this issue:
0.5.6 of DexCount plugin, it is referenced in project root build.gradle
