### ISSUE TITLE
Incompatibility with Gradle Plugin 3.0.0-alpha1

### ISSUE THREAD

**Issue by edenman** [KeepSafe/dexcount-gradle-plugin#161]
build script deps:
```
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    classpath 'com.android.tools.build:gradle:3.0.0-alpha1'
    classpath 'com.google.gms:google-services:3.0.0'
    classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.6.4'
```
fails with message "Not valid." stacktrace:
```
 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':countDebugDexMethods'.
   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:98)
   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:68)
   at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:60)
   at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
   at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
   at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
   at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
   at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:248)
   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:239)
   at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:114)
   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:239)
   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:226)
   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:120)
   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:101)
   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:95)
   at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:527)
   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:95)
   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
   at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
   at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
 Caused by: java.lang.RuntimeException: Not valid.
   at com.android.ide.common.build.ApkData.getMainOutputFile(ApkData.java:136)
   at com.android.build.gradle.internal.api.BaseVariantOutputImpl.getOutputFile(BaseVariantOutputImpl.java:60)
   at com.android.build.gradle.internal.api.ApkVariantOutputImpl_Decorated.getOutputFile(Unknown Source)
   at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
   at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
   at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
   at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
   at com.android.build.gradle.internal.api.ApkVariantOutputImpl_Decorated.getProperty(Unknown Source)
   at com.getkeepsafe.dexcount.DexMethodCountTask.checkIfApkExists(DexMethodCountTask.groovy:288)
   at com.getkeepsafe.dexcount.DexMethodCountTask.countMethods(DexMethodCountTask.groovy:59)
   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:139)
   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:132)
   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:706)
   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:689)
   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
   at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:114)
   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
   ... 26 more
```

**Comment by benjamin-bader** [comment]
Hm.  Thanks for the stacktrace; I'll take a look.

**Comment by benjamin-bader** [comment]
The APIs we rely on for getting at variants have been broken, because not all variant tasks are created.  Hooray for faster builds, but it does mean that `dexcount` will not function with the new build tools.  An alternate API is planned, but has not been delivered.

https://developer.android.com/studio/preview/features/new-android-plugin-migration.html#variant_api

**Comment by mikepenz** [comment]
@benjamin-bader I am not 100% sure if it really helps you, but I had the same log output  with something else in my project:
```gradle
getMainOutputFile is no longer supported.  Use getOutputFileName if you need to determine the file name of the output.
```

I have a method in my project renaming the output file of the apk to something else, and it gave me the exact same message... So I changed it as shown below.

<img width="1564" alt="screen shot 2017-06-04 at 23 35 38" src="https://cloud.githubusercontent.com/assets/1476232/26765566/9cbc4470-497e-11e7-9d90-d89b2ed52a7c.png">

(There's a really high possibility that this is just a single problem here, as I can see that the variant API might break all the rest too :D)

**Comment by benjamin-bader** [comment]
Thanks, Mike.  The word from on high is that we should be relying on the `package` family of tasks to get at build outputs; I'm looking in to that today.  With some luck, I'll have a new version in the next few days - no promises though!

**Comment by benjamin-bader** [comment]
I've just pushed a snapshot build to Sonatype; please try it and let me know how it works for you:

```
buildscript {
  repositories {
    // other repos should come first
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
  }

  dependencies {
    classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.7.0-SNAPSHOT'
  }
}
```

**Comment by jmfayard** [comment]
@benjamin-bader 
It does not work for me

```
:app:packageDevDebug (Thread[Daemon worker Thread 18,5,main]) completed. Took 0.674 secs.
:app:countDevDebugDexMethods (Thread[Daemon worker Thread 18,5,main]) started.
:app:countDevDebugDexMethods
Putting task artifact state for task ':app:countDevDebugDexMethods' into context took 0.0 secs.
Executing task ':app:countDevDebugDexMethods' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:app:countDevDebugDexMethods FAILED
:app:countDevDebugDexMethods (Thread[Daemon worker Thread 18,5,main]) completed. Took 0.003 secs.
:app:buildInfoGeneratorDevDebug (Thread[Daemon worker Thread 18,5,main]) started.
:app:buildInfoGeneratorDevDebug
Putting task artifact state for task ':app:buildInfoGeneratorDevDebug' into context took 0.0 secs.
Executing task ':app:buildInfoGeneratorDevDebug' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:app:buildInfoGeneratorDevDebug (Thread[Daemon worker Thread 18,5,main]) completed. Took 0.002 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:countDevDebugDexMethods'.
> Cannot access first() element from an empty array

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:countDevDebugDexMethods'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:98)
	at 

Caused by: java.util.NoSuchElementException: Cannot access first() element from an empty array
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.first(DefaultGroovyMethods.java:8976)
	at org.codehaus.groovy.runtime.dgm$220.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at com.getkeepsafe.dexcount.DexMethodCountTask.fileToCount(DexMethodCountTask.groovy:315)
	at com.getkeepsafe.dexcount.DexMethodCountTask.checkIfApkExists(DexMethodCountTask.groovy:309)
	at com.getkeepsafe.dexcount.DexMethodCountTask.countMethods(DexMethodCountTask.groovy:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)

```

**Comment by benjamin-bader** [comment]
@jmfayard thanks - if you have time, would you please file a new issue with this stacktrace, and also include:
- What android plugin version are you on (I've tested with 3.0.0-alpha3, but not alphas 1 or 2)
- Are you building an APK or a library?
- Are you renaming your output file somehow?
- What gradle command were you using to build?

It's weird because this error makes it seems as if your build just didn't put your build output into the directory it says it would...
