### ISSUE TITLE
Error with Studio 3.0.3  / dexcount-gralde-plugin:0.7.0-SNAPSHOT

### ISSUE THREAD

**Issue by jmfayard** [KeepSafe/dexcount-gradle-plugin#168]
I have a gradle error with Studio 3.0.3  / dexcount-gradle-plugin:0.7.0-SNAPSHOT

I'm building an apk with the run button from android studio, which calls `gadlew app:assembleDevDebug`

What I notice:

- when I first apply the plugin, the build fails
- `Build > Rebuild project` works
- If I add a method and do an incremental build, gradle fails

First mentionned here  https://github.com/KeepSafe/dexcount-gradle-plugin/issues/161

Gradle console output

```
:app:packageDevDebug (Thread[Daemon worker Thread 18,5,main]) completed. Took 0.674 secs.
:app:countDevDebugDexMethods (Thread[Daemon worker Thread 18,5,main]) started.
:app:countDevDebugDexMethods
Putting task artifact state for task ':app:countDevDebugDexMethods' into context took 0.0 secs.
Executing task ':app:countDevDebugDexMethods' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:app:countDevDebugDexMethods FAILED
:app:countDevDebugDexMethods (Thread[Daemon worker Thread 18,5,main]) completed. Took 0.003 secs.
:app:buildInfoGeneratorDevDebug (Thread[Daemon worker Thread 18,5,main]) started.
:app:buildInfoGeneratorDevDebug
Putting task artifact state for task ':app:buildInfoGeneratorDevDebug' into context took 0.0 secs.
Executing task ':app:buildInfoGeneratorDevDebug' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:app:buildInfoGeneratorDevDebug (Thread[Daemon worker Thread 18,5,main]) completed. Took 0.002 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:countDevDebugDexMethods'.
> Cannot access first() element from an empty array

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:countDevDebugDexMethods'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:98)
	at 

Caused by: java.util.NoSuchElementException: Cannot access first() element from an empty array
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.first(DefaultGroovyMethods.java:8976)
	at org.codehaus.groovy.runtime.dgm$220.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at com.getkeepsafe.dexcount.DexMethodCountTask.fileToCount(DexMethodCountTask.groovy:315)
	at com.getkeepsafe.dexcount.DexMethodCountTask.checkIfApkExists(DexMethodCountTask.groovy:309)
	at com.getkeepsafe.dexcount.DexMethodCountTask.countMethods(DexMethodCountTask.groovy:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```

Gradle config

```
buildscript {
  repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
  }
  dependencies {
    classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.7.0-SNAPSHOT'
  }
}
```

My environment

```
Android Studio  3.0 Canary 3, AI-171.4056697, 201705312241,
AI-171.4056697, JRE 1.8.0_112-release-b736x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.5 unknown, screens 1920x1080, 1440x900
Gradle version 4.0
Android Plugin 3.0.0-alpha3
Compile Sdk Version : Api 25: Android 7.1.1
Kotlin : 1.1.2-4
Build Tools Version: 25.0.2
Android- SDK Build-Tools 26-rc2
```

**Comment by benjamin-bader** [comment]
Hey, thanks for the bug report!  I appreciate the detailed observations - I haven't run into this crash before, but I typically build on the command line.  I'll dive in and see what I can find.

**Comment by jdrider** [comment]
I have the same environment listed in the original report and have noticed that command line builds complete successfully, but builds from within AS fail with the error listed.

**Comment by benjamin-bader** [comment]
It sounds like AS is doing something odd with the `:app:packageDevDebug` task, then.  The crash indicates that the output directory for that task, which _should_ contain the built APK, is empty.  Time to dive in to their source code!

**Comment by benjamin-bader** [comment]
I just got a reliable repro going, and it is now clear what's going on.

The failing builds are Instant Run builds.  The plugin is expecting that the `package` task produces an APK, but that is not true of Instant Run.  I'm looking in to a fix, but short-term you could disable Instant Run and dexcount will work.

I may end up just disabling it for incremental builds, since the extra time spent counting kind of defeats the purpose of "Instant" Run; we'll see.

**Comment by jmfayard** [comment]
Instant Run works with split apk, that may be the reason

> I may end up just disabling it for incremental builds, since the extra time spent counting kind of defeats the purpose of "Instant" Run; we'll see.

That makes sense!

**Comment by benjamin-bader** [comment]
After talking with one of the built-tools devs at Google, it sounds like disabling counting for Instant Run is the way to go.  Will update here when that lands.
