### ISSUE TITLE
Can't build when renaming apk

### ISSUE THREAD

**Issue by Gounlaf** [KeepSafe/dexcount-gradle-plugin#220]
Hi,

I got issue with version >= 8.0.0. No problem with version 0.7.3

```
Error:A problem was found with the configuration of task ':mymodulename:countDebugDexMethods'.
> File '/my/project/full/path/build/outputs/apk/debug/mymodulename-debug.apk' specified for property 'inputFile' does not exist.
```

The problem is that I rename the final apk like this (in "mymodulename" build.gradle):

```
[...]

android {
    [...]
    android.applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "mymodulename-${variant.name}-${variant.versionName}-${getGitHash()}.apk"
        }
    }
    [...]
}

[...]
```

I've found this somewhere on github or strackoverflow, don't remember. Maybe I'm doing it wrong.

Last part of build with `--stacktrace` option:

```
[...]
:mymodulename:transformResourcesWithMergeJavaResForDebug
:mymodulename:packageDebug
:mymodulename:countDebugDexMethods FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':mymodulename:countDebugDexMethods'.
> File '/my/project/full/path/build/outputs/apk/debug/mymodulename-debug.apk' specified for property 'inputFile' does not exist.


* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskValidationException: A problem was found with the configuration of task ':mymodulename:countDebugDexMethods'.
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.InvalidUserDataException: File '/my/project/full/path/build/outputs/apk/debug/mymodulename-debug.apk' specified for property 'inputFile' does not exist.
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:47)
	... 23 more

```

Thanks for your help (and thanks for your plugin!),

Regards.

**Comment by benjamin-bader** [comment]
Hi, thanks for the report.  What version of the Android Build Tools are you using?

**Comment by Gounlaf** [comment]
Hi @benjamin-bader,

I've tested with:
* build tools versions 26.0.2 (released recently)
* build tools versions 26.0.1
* both on Android Studio 3 Beta 6

**Comment by benjamin-bader** [comment]
Sorry, I misspoke - I'm asking about the Gradle plugin version (`com.android.build.tools:gradle:X.X.X`).  If you're on Studio 3, beta 6, I'm assuming you're on the equivalent tools version.  I'll see if I can repro.

**Comment by Gounlaf** [comment]
>  If you're on Studio 3, beta 6, I'm assuming you're on the equivalent tools version. I'll see if I can repro.
* Yes: `com.android.tools.build:gradle:3.0.0-beta6`

**Comment by plastiv** [comment]
Not a solution, but this funtionality removal is documented here: https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#variant_output

Quote:

> However, more complicated tasks that involve accessing outputFile objects no longer work. That's because variant-specific tasks are no longer created during the configuration stage. This results in the plugin not knowing all of its outputs up front, but it also means faster configuration times.

There may or may not be new api provided for the rename apk use case. 

I would suggest you to look into Copy task which will duplicate apk at your folder instead of renaming the android plugin properties. Similar to: https://stackoverflow.com/a/44637367/624706

**Comment by benjamin-bader** [comment]
Sorry to have let this sit for so long!  To be frank, the constant churn around this particular part of the Android Gradle Plugin has been pretty demotivating for me.  Now that Studio 3.0 is out of beta and is officially released, I feel a little better about investigating its current behavior and fixing this plugin to match.

No timeline, but I'm still here!

**Comment by KERiii** [comment]
@benjamin-bader Are you planning to release a new version with this fix in the near future?

**Comment by benjamin-bader** [comment]
Hi, I've just pushed a new build (version 0.8.2) to Maven Central, which ought to address this bug.  Thanks for your patience, everyone!  Please let me know whether this fixes things for you.

**Comment by vRallev** [comment]
Working fine here 👍

**Comment by benjamin-bader** [comment]
If everyone here is satisfied that the bug is fixed in the new release, I'll close this issue in the next few days - please chime in if you're still hitting this issue!

**Comment by Gounlaf** [comment]
Hi @benjamin-bader,

I will test asap and keep you updated. Thanks

**Comment by benjamin-bader** [comment]
@Gounlaf have you had a chance to test?  Please let me know.  I'm going to close this on Wednesday, unless you tell me that you're still hitting this issue.

Thanks!

**Comment by benjamin-bader** [comment]
Since I haven't heard anything to the contrary over the past three weeks, I'll assume this issue is resolved.  Thanks to everyone who reported it!
