### ISSUE TITLE
Issue when signing apk with app bundle

### ISSUE THREAD

**Issue by mhdtouban** [KeepSafe/dexcount-gradle-plugin#246]
I was trying out the AS 3.2 app bundle feature, after signing the bundle apk, and upgrade an existing apk from universal to a targeted apk, I got a crash on launch with missing realm ISO files. 
Is this caused by relinker or realm or even app bundle ?
  java.lang.RuntimeException: Unable to create application com.elixir.Onlivery_v3.OnliveryApplication: com.getkeepsafe.relinker.MissingLibraryException: lib/armeabi/librealm-jni.so
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: com.getkeepsafe.relinker.MissingLibraryException: lib/armeabi/librealm-jni.so
        at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(SourceFile:85)
        at com.getkeepsafe.relinker.ReLinkerInstance.a(SourceFile:180)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(SourceFile:136)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(SourceFile:70)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(SourceFile:57)
        at io.realm.internal.RealmCore.loadLibrary(SourceFile:60)
        at io.realm.Realm.init(SourceFile:258)
        at com.idea.IdeaApplication.a(SourceFile:49)
        at com.idea.IdeaApplication.onCreate(SourceFile:44)
        at com.elixir.Onlivery_v3.OnliveryApplication.onCreate(SourceFile:46)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)

**Comment by benjamin-bader** [comment]
This is not a dexcount problem, and probably isn't a relinker problem either.  It seems like a Realm problem.  Please open an issue with them.
