### ISSUE TITLE
StringIndexOutOutBoundsException

### ISSUE THREAD

**Issue by jdrider** [KeepSafe/dexcount-gradle-plugin#6]
**Dependencies**
```
com.android.tools.build:gradle:1.3.0-beta4
com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.2.0-SNAPSHOT
Gradle 2.5 (Occurs with 2.4 as well)
```

**Stack Trace**
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':stylini
ty:assembleDevelopmentDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
ute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
e(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
ter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
e(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker.execute(DefaultTaskGraphExecuter.java:208)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker.execute(DefaultTaskGraphExecuter.java:186)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.processTask(AbstractTaskPlanExecutor.java:62)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE
xecutorImpl.java:40)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range:
 0
        at java_lang_CharSequence$charAt$0.call(Unknown Source)
        at com.getkeepsafe.dexcount.PackageTree.<init>(PackageTree.groovy:24)
        at com.getkeepsafe.dexcount.PackageTree.addInternal(PackageTree.groovy:3
6)
        at com.getkeepsafe.dexcount.PackageTree.this$2$addInternal(PackageTree.g
roovy)
        at com.getkeepsafe.dexcount.PackageTree$this$2$addInternal$0.call(Unknow
n Source)
        at com.getkeepsafe.dexcount.PackageTree.addInternal(PackageTree.groovy:4
3)
        at com.getkeepsafe.dexcount.PackageTree.this$2$addInternal(PackageTree.g
roovy)
        at com.getkeepsafe.dexcount.PackageTree$this$2$addInternal$0.call(Unknow
n Source)
        at com.getkeepsafe.dexcount.PackageTree.addInternal(PackageTree.groovy:4
3)
        at com.getkeepsafe.dexcount.PackageTree.this$2$addInternal(PackageTree.g
roovy)
        at com.getkeepsafe.dexcount.PackageTree$this$2$addInternal$0.call(Unknow
n Source)
        at com.getkeepsafe.dexcount.PackageTree.addInternal(PackageTree.groovy:4
3)
        at com.getkeepsafe.dexcount.PackageTree.this$2$addInternal(PackageTree.g
roovy)
        at com.getkeepsafe.dexcount.PackageTree$this$2$addInternal$0.call(Unknow
n Source)
        at com.getkeepsafe.dexcount.PackageTree.addInternal(PackageTree.groovy:4
3)
        at com.getkeepsafe.dexcount.PackageTree.add(PackageTree.groovy:28)
        at com.getkeepsafe.dexcount.PackageTree$add.call(Unknown Source)
        at com.getkeepsafe.dexcount.DexMethodCountTask$_getPackageTree_closure3.
doCall(DexMethodCountTask.groovy:112)
        at com.getkeepsafe.dexcount.DexMethodCountTask.getPackageTree(DexMethodC
ountTask.groovy:108)
        at com.getkeepsafe.dexcount.DexMethodCountTask_Decorated.getPackageTree(
Unknown Source)
        at com.getkeepsafe.dexcount.DexMethodCountTask.countMethods(DexMethodCou
ntTask.groovy:41)
        at com.getkeepsafe.dexcount.DexMethodCountTask$countMethods.call(Unknown
 Source)
        at com.getkeepsafe.dexcount.DexMethodCountPlugin$_applyAndroid_closure1_
closure2_closure3.doCall(DexMethodCountPlugin.groovy:54)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(Abstra
ctTask.java:554)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(Abstra
ctTask.java:535)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
```

**Comment by benjamin-bader** [comment]
Hm, definitely a bug in the SNAPSHOT build, nothing to do with Android Studio.  I'd recommend using version 0.1.1  Thanks for reporting.

**Comment by oneEyedOdin** [comment]
I updated the title.  I've been using the 0.2.0-SNAPSHOT build since June 15th and this exception only came up when I upgraded to AS 1.3RC1 so I thought they were related.  I now see it was just a coincidence and the changes from 123688a9b9235cfefb34790ca3f6a4d7eee2cd70 is where the issue came from.

**Comment by benjamin-bader** [comment]
I just updated master.  Among the changes are what should be a bugfix.

It's hard to say without having seen the input to the plugin from your project (i.e. all of the classnames), but I'm guessing that you had classes with unusual names - `$$GeneratedClass$$` or the like - which is the only thing thing I can think would have caused this exception.  The updated version no longer attempts to prettify class names, so these should work fine.

Let me know if you still see problems.

**Comment by jdrider** [comment]
That's highly likely.  I use Butterknife and Retrolambda so I have classes with names like ```Class$$ViewBinder$1.class``` and ```Class$$Lambda$1.class```.

I tried the latest snapshot build and it is working now.
