### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by IgorGanapolsky** [KeepSafe/dexcount-gradle-plugin#62]
Hello,
my build fails, and your plugin does not show the dex count:
> UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
        at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:484)
        at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:261)
        at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:473)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:161)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

Please advise,
Igor

**Comment by benjamin-bader** [comment]
Hi Igor,

This is an unfortunate limitation of the plugin.  It relies on having an APK from which to count method references.  If your build fails, there is no APK to count.  It's ironic that a method-limit-exceeded failure will prevent the method count from happening.

The best suggestion I have, if you wish to know how far over the limit you are, is to temporarily enable multidex.

Ben

**Comment by IgorGanapolsky** [comment]
@benjamin-bader  Thanks for the heads up.  @changetip $1

**Comment by changetip** [comment]
Hi @benjamin-bader, @IgorGanapolsky sent you a tip worth 2,413 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/944242)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
