### ISSUE TITLE
Cannot write to file '/build/outputs/dexcount/debugChart' specified for property 'chartDir' as it is a directory.

### ISSUE THREAD

**Issue by jaredsburrows** [KeepSafe/dexcount-gradle-plugin#84]
## Command:

`./gradlew clean assembleDebug countDebugDexMethods`

## Error:
```
:assembleDebug
Total methods in -debug.aar: 2154 (3.29% used)
Total fields in -debug.aar:  1036 (1.58% used)
Methods remaining in -debug.aar: 63381
Fields remaining in -debug.aar:  64499
:countDebugDexMethods FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':countDebugDexMethods'.
> Cannot write to file '/build/outputs/dexcount/debugChart' specified for property 'chartDir' as it is a directory.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.439 secs
```

**Comment by jaredsburrows** [comment]
However, if you specify `-x` which should "skip" and prevent the task from running, it works just fine:
```
:assembleDebug
Total methods in -debug.aar: 2154 (3.29% used)
Total fields in -debug.aar:  1036 (1.58% used)
Methods remaining in -debug.aar: 63381
Fields remaining in -debug.aar:  64499

BUILD SUCCESSFUL

Total time: 7.081 secs
$ gradle clean assembleDebug -x countDebugDexMethods 
```

**Comment by benjamin-bader** [comment]
I've never used this Gradle option.  It makes me wonder just how many dexcount tasks are running!  Or rather, what their names are.

**Comment by jaredsburrows** [comment]
Yeah. It looks like calling it directly fails and excluding(`-x`) seems to allow it to pass. :(

**Comment by benjamin-bader** [comment]
Are you able to share your build.gradle and project structure?  It might be helpful to see those.

**Comment by jaredsburrows** [comment]
It is a very basic multi-project build structure.
```
$ tree -L 2
.
|-- README.md
|-- build.gradle
|-- blah
|   |-- build.gradle
|   |-- src
|-- blah2
|   |-- build.gradle
|   `-- src
```

**Comment by Macarse** [comment]
It is happening to me as well.

if I run `./gradlew assembleDebug` works fine but if I run `./gradlew countDebugDexMethods` I get that error.

**Comment by chubbard** [comment]
I also have this happening in my build as well when I run countDebugDexMethods directly.  I'm using a multi-project setup.  My project build file is as follows:

`    
    buildscript {
     repositories {
        jcenter()
     }
     dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0'
        classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.5.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
     }
    }
    allprojects {
       repositories {
          jcenter()
          maven {
              url "https://jitpack.io"
          }
        }
     }
    task clean(type: Delete) {
       delete rootProject.buildDir
    }
`

The configuration in my app project is something like this for dexcount:

`   apply plugin: 'com.android.application'
    apply plugin: 'com.getkeepsafe.dexcount'
    
    android {
        compileSdkVersion 23
        buildToolsVersion "23.0.2"
        defaultConfig {
          ...
         }

        signedConfigs {
          ...
        }

       buildTypes {
         ...
       }
    }

    dexcount {
       format = "list"
       includeClasses = false
       includeFieldCount = true
       includeTotalMethodCount = true
       orderByMethodCount = true
       verbose = false
       maxTreeDepth = Integer.MAX_VALUE
       teamCityIntegration = false
    }

    dependencies {
      ...
    }
`

**Comment by benjamin-bader** [comment]
Try this: `./gradlew --stacktrace countDebugDexMethods`

Please paste the exception here, it will be very helpful to me.  Thanks!

**Comment by chubbard** [comment]
gradle --stacktrace countDebugDexMethods
	Incremental java compilation is an incubating feature.
	:app:countDebugDexMethods FAILED

	FAILURE: Build failed with an exception.

	* What went wrong:
	A problem was found with the configuration of task ':app:countDebugDexMethods'.
	> Cannot write to file '/Users/charliehubbard/projects/android/AmplifiedNextGen/app/build/outputs/dexcount/debugChart' specified for property 'chartDir' as it is a directory.

	* Try:
	Run with --info or --debug option to get more log output.

	* Exception is:
	org.gradle.api.tasks.TaskValidationException: A problem was found with the configuration of task ':app:countDebugDexMethods'.
		at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:55)
		at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
		at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
		at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
		at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
		at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
		at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
		at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
		at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
		at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
		at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
		at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
		at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
		at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
		at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
		at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
		at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
		at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
		at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
		at org.gradle.internal.Factories$1.create(Factories.java:22)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
		at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
		at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
		at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
		at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
		at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
		at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
		at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
		at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
		at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
		at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
		at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
		at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
		at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
		at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
		at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
		at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
		at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
		at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
		at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
		at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
		at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
		at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
		at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
		at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
		at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
		at org.gradle.launcher.Main.doAction(Main.java:33)
		at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
		at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
		at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
		at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	Caused by: org.gradle.api.InvalidUserDataException: Cannot write to file '/Users/charliehubbard/projects/android/AmplifiedNextGen/app/build/outputs/dexcount/debugChart' specified for property 'chartDir' as it is a directory.
		at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:47)
		... 53 more


	BUILD FAILED

	Total time: 8.142 secs
